services:
  rustfs:
    container_name: gvd-frs-media
    image: rustfs/rustfs:latest
    environment:
      RUSTFS_ROOT: /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
    restart: unless-stopped

volumes:
  rustfs_data:
